default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_analytics_development
  username: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

test:
  <<: *default
  database: hotel_analytics_test
  username: postgres
  password: postgres
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

production:
  primary:
    <<: *default
    database: hotel_analytics_production
    username: postgres
    password: postgres
    host: localhost
  cache:
    <<: *default
    database: hotel_analytics_cache_production
    username: postgres
    password: postgres
    host: localhost
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: hotel_analytics_queue_production
    username: postgres
    password: postgres
    host: localhost
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: hotel_analytics_cable_production
    username: postgres
    password: postgres
    host: localhost
    migrations_paths: db/cable_migrate
